### ISSUE TITLE
[Execution] Add container action support to ray-worker (already done in single-threaded worker).

### ISSUE THREAD

**Issue by sven1977** [rlgraph/rlgraph#11]
Container actions come as a dict from `Agent.get_action()` where each key contains a batch of values.

This format needs to be flipped (to a list of dicts) via:

ret = [{key: value[i] for key, value in ret.items()} for i in range(len(ret[next(iter(ret))]))] (ret is the session-returned dict)

... before sending single actions to an env.

NOTE: The original session output (no flipping) is needed when python-buffering and/or observing via `Agent.observe()`!

**Comment by michaelschaarschmidt** [comment]
Done.
