### ISSUE TITLE
[Core] Refactor define_graph_api

### ISSUE THREAD

**Issue by michaelschaarschmidt** [rlgraph/rlgraph#15]
The current signature of define_graph_api is weird and leads to pep8 warnings in all agents because we pass through arbitrary other args. Splitting the list of subcomponents also seems suboptimal,
maybe we should pass them as a dict and look them up where needed. Long lines like

```
        preprocessor, merger, memory, splitter, policy, exploration, loss_function, optimizer, value_function, \
            vf_optimizer = sub_components
```

should be avoided.

**Comment by sven1977** [comment]
The define_graph_api method signature is now generic via *args, **kwargs and all superfluous code has been removed.
