### ISSUE TITLE
[Core] Update or remove component visualization utils

### ISSUE THREAD

**Issue by michaelschaarschmidt** [rlgraph/rlgraph#27]
The current visualization utils refer to an outdated component API model and should either be deprecated entirely or updated so we can produce visualizations again (desirable but not high priority).

**Comment by sven1977** [comment]
We will provide an updated version of the currently outdated mermaid tool with enhanced RLgraph debugging support. This visualization tool will also be used to display problematic/faulty sub-graphs and sub-meta-graphs during the RLgraph build process.

Motivation:
Finding and fixing errors during the `Agent.build()` process is - as far as we know - the most time consuming aspect of RLgraph algo-implementation and development work.

**Comment by sven1977** [comment]
With 0.5.4, we now have a prototype for a debug visualization util that automatically builds sub-graphs and visualizes them in the browser (pdf) using GraphViz. In this visualized sub-graph (only the relevant parts of the Agent are shown to reduce information overload), one can see immediately where Space (shape/type) problems occurred.

Closing this issue.
