### ISSUE TITLE
Allow providing the method to call directly in GraphExecutor.execute()

### ISSUE THREAD

**Issue by janislavjankov** [rlgraph/rlgraph#44]
Currently execute() accepts the method name provided as string, which prevent linters to detect typos or changes due to refactoring. I propose to allow passing the method directly - linters and auto-complete works.
Current state:
```python
graph_executor.execute("get_policy_weights")
```
Proposed change:
```python
graph_executor.execute(self.root_component.get_policy_weights)
```

**Comment by michaelschaarschmidt** [comment]
Thanks for bringing up the API improvement, closed via PR

https://github.com/rlgraph/rlgraph/commit/3ab948f2091ce36d2341b47b82f92986bf69b0e9
