### ISSUE TITLE
[Core] Clarify use of summaries.

### ISSUE THREAD

**Issue by michaelschaarschmidt** [rlgraph/rlgraph#56]
TODOs:

- Fix potential bugs in summary specs
-Add/Create FAQ how to use summaries
- Create example configs in examples folder

**Comment by sven1977** [comment]
I'll create an example script for a learning DQNAgent with summaries on the NN vars.

**Comment by sven1977** [comment]
This has been completed and can be tried out in the `global_training_time_step_and_summaries`-branch (file: rlgraph/examples/dqn_cartpole_with_tf_summaries.py).

![image](https://user-images.githubusercontent.com/5839854/53510343-10b4ea80-3abe-11e9-9ee9-1455423fe7b7.png)

There was a bug where the summary_regexp was not passed into the graph_builder and the global_training_timestep of the graph executor was never properly increased.

After testing confirmation, this branch will be merged into master.

![image](https://user-images.githubusercontent.com/5839854/53510377-21656080-3abe-11e9-84be-04c9f8302935.png)
