### ISSUE TITLE
Checkpoints not created

### ISSUE THREAD

**Issue by theSoenke** [rlgraph/rlgraph#65]
It seems that there are no checkpoints created when a saver_spec is used. My config contains the following entry:

```
   "saver_spec": {
        "save_secs": 600,
        "max_checkpoints": 5
    },
```

With this config an initial checkpoint is created but after that no new checkpoints are stored. I'm using the ApexExecutor with Tensorflow backend for this.

Am I missing something or is there an issue with the checkpoints?

**Comment by michaelschaarschmidt** [comment]
Hm, that should not happen, can you check if this line

https://github.com/rlgraph/rlgraph/blob/master/rlgraph/graphs/tensorflow_executor.py#L397

goes into the if to create a saver hook?

**Comment by theSoenke** [comment]
Yes, the saver hook is definitely created in that line

**Comment by theSoenke** [comment]
Interesting. Now the checkpoints seem to be working in a larger run. No idea why it did work before on my machine. Definitely waited long enough. Will close this issue for now and have a closer look what might have caused this

**Comment by michaelschaarschmidt** [comment]
Ok thank you let us know/reopen when you know what's going on. Seems like should work in principle.
