### ISSUE TITLE
[Core] Move update controls and logic from Worker to Agent(s).

### ISSUE THREAD

**Issue by sven1977** [rlgraph/rlgraph#73]
Every `Agent` has a different updating logic (`update_spec`), with or w/o synching, updating only after n timesteps, n episodes, etc..
The `Worker` class should not handle this logic.
Maybe we can simply move the `update_if_necessary` method from `Worker` to `Agent`.

**Comment by michaelschaarschmidt** [comment]
I disagree because of the design separation - the agents should expose an API. Workers like the single threaded worker or the ray executors consume the API. Fundamentally, It is the not task of an API to decide when and how to execute that API.

**Comment by sven1977** [comment]
Yes, that's all correct. Moved the `update_spec` into the `Worker` instead. Will be released in next version (0.6.x). as `UpdateRules` objects with type-safety (no more spec dicts). Closing this issue.
